_target_: transformers.TrainingArguments

num_train_epochs: 4
evaluation_strategy: "epoch"
save_strategy: "epoch"
save_total_limit: 2
load_best_model_at_end: True

output_dir: ${paths.checkpoints_dir}
weight_decay: ${model.optimizer.weight_decay}
learning_rate: ${model.optimizer.learning_rate}
per_device_train_batch_size: ${data.train_batch_size}
per_device_eval_batch_size: ${data.eval_batch_size}
