base_model: "dumitrescustefan/bert-base-romanian-uncased-v1"
max_seq_length: 96

optimizer:
  weight_decay: 0.08
  learning_rate: 1e-4

key_labels: "labels"
key_logits: "logits"

classifier_dropout: 0.43

constructor:
  _target_: transformers.AutoModelForSequenceClassification.from_pretrained
  pretrained_model_name_or_path: ${model.base_model}
  num_labels: ${data.num_labels}
  id2label: ${id2label:${data.labels}}
  label2id: ${label2id:${data.labels}}
  classifier_dropout: ${model.classifier_dropout}

constructor_predict:
  _target_: transformers.AutoModelForSequenceClassification.from_pretrained
  _partial_: true
