# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: coroseof.yaml
  - model: bert_ro_dumitrescu.yaml
  - paths: default.yaml

# task name, determines output directory path
task_name: "predict"

# stage name; used in the initializing the dataset
stage: "predict"

# seed for random number generators in pytorch, numpy and python.random
seed: 66
